### ISSUE TITLE
localhost:3000 not accessible

### ISSUE THREAD

**Issue by melalj** [convox-examples/rails-sidekiq#1]
Hello,

Maybe I'm missing something, but when I tried to start the example on a local environment 'using `convox start`, I got a connection refused for: `localhost:3000`, `0.0.0.0:3000`and also the output of `$(boot2docker ip):3000`

While on the log I got:

    web      | => Booting WEBrick
    web      | => Rails 4.2.1 application starting in development on http://0.0.0.0:3000
    web      | => Run `rails server -h` for more startup options
    web      | => Ctrl-C to shutdown server

I tried to deploy it to the production and it worked.
Any idea how to fix this?

**Comment by mattmanning** [comment]
This has been updated and should now work with:

`$(docker-machine ip <your machine>):3000`
